### ISSUE TITLE
FAST Checklist review for IFT

### ISSUE THREAD

**Issue by svgeesus** [w3c/IFT#32]
The following sections of the [FAST checklist](https://w3c.github.io/apa/fast/checklist.html) seem to apply to the [Incremental Font Transfer](https://www.w3.org/TR/IFT/) specification:

**If technology allows visual rendering of content**

- [ ] _There is a defined way for a non-visual rendering to be created._ Does not apply; this specification is about the fonts used to create the visual rendering from the content, and not the content itself (which will define how to create non-visual rendering such as text to speech)
- [x] _Content can be resized._ Yes, the font can be used to render text at different sizes
- [ ] _Luminosity and hue contrast can adapt to user requirements._ Does not apply; the CSS or whatever is requesting the font controls this, not the font.
- [ ] _Text presentation attributes can be changed._ Does not apply; the CSS or whatever is requesting the font controls this, not the font.
- [ ] _Visual presentation of pointers and cursors can be adjusted._ Does not apply; the CSS or whatever is requesting the font controls this, not the font.
- [ ] _Changing content presentation does not render it unreadable._ Does not apply; the CSS or whatever is requesting the font controls this, not the font.
- [ ] _Technology does not allow blinking or flashing of content, or provides a feature for users to quickly turn it off or permanently disable it._ Does not apply; the CSS or whatever is requesting the font controls this, not the font.
- [ ] _It is possible to make navigation order correspond to the visual presentation._ Does not apply; the CSS or whatever is requesting the font controls this, not the font.

**If technology defines an API**

- [ ] _If the API can be used for structured content, it provides features to represent all aspects of the content including hidden accessibility features._ Does not apply; this API transfers just the fonts, not the structured content
- [ ] _If the API relies on user agents to generate a user interface, the specification provides guidance about accessibility requirements needed to enable full interaction with the API._  Does not apply; this API does not require a user interface

**Comment by svgeesus** [comment]
Closing as [A11y review concluded with no issues](https://github.com/w3c/a11y-request/issues/16#issuecomment-930347430)

**Comment by svgeesus** [comment]
The above checklist is also correct for the [9 July 2024 IFT WD](https://www.w3.org/TR/2024/WD-IFT-20240709/)
