### ISSUE TITLE
I18n checklist answers for IFT

### ISSUE THREAD

**Issue by svgeesus** [w3c/IFT#36]
Short i18n review checklist is [here](http://w3c.github.io/i18n-activity/reviews/shortchecklist)

1. [ ] _If the spec (or its implementation) contains any natural language text that will be read by a human (this includes error messages or other UI text, JSON strings, etc, etc),_

    No. This is a client-server protocol to incrementally transfer Web fonts, which happens transparently in the background.
    
2. [ ] _If the spec (or its implementation) allows content authors to produce typographically appealing text, either in its own right, or in association with graphics._

    No differently to traditional (transferred in their entirety) webfonts. Just faster.

3. [ ] _If the spec (or its implementation) allows the user to point into text, creates text fragments, concatenates text, allows the user to select or step through text (using a cursor or other methods), etc._

    No

4. [x] _If the spec (or its implementation) allows searching or matching of text, including syntax and identifiers_

    Not exactly. The set of characters to be rendered  in a given font in a document is matched against the character repertoire of the font, and font subset update requests are made to get glyphs for any missing characters.

5. [ ] _If the spec (or its implementation) sorts text_

    No

6. [ ] _If the spec (or its implementation) captures user input_

    No

7. [ ] _If the spec (or its implementation) deals with time in any way that will be read by humans and/or crosses time zone boundaries_

    No

8. [ ] _If the spec (or its implementation) allows any character encoding other than UTF-8._

    Textual content is not transferred by this specification

9. [ ] _If the spec (or its implementation) defines markup._

    No

10. [ ] _If the spec (or its implementation) deals with names, addresses, time & date formats, etc_

    No

11. [ ] _If the spec (or its implementation) describes a format or data that is likely to need localization._

    No

12. [ ] _If the spec (or its implementation) makes any reference to or relies on any cultural norms_

    No
